### ISSUE TITLE
Tasks - 03.12.2024

### ISSUE THREAD

**Issue by GlycerolVeinz** [GlycerolVeinz/sinSemestralWork#18]
# Tasks:
- [x] Finish what's left from #12 
- [x] #17 
- [x] Fix problems that we had with today's consultation
  - [x] ADM
    - [x] Multiplicity
    - [x] Subscription + Client tier (either make it more readable or add more notes to it)
    - [ ] **Probably good idea** would be to somehow merge ClubAdmin, Performer, Customer into one class (inheritance if needed) 
  - [x]  Use - case
    - [ ] **REMOVE REDUNDANT INFORMATION** (e.g. if the use-case is talking about one thing don't do 5 steps of navigation (navigation should be in wire-frames navigation))
    - [x] @anokhver decide if you want to simplify that one big use-case or split it into 3, let us know.
    - [ ] Independently of who is the main actor the scenario should use word *User*. Please rewrite.
  - [x] Wire-frames
    - [ ] Add notes wherever there could be something ambiguous
    - [ ] Try adding navigation using `component child diagram` wherever you are already have connection between wire-frames
    - [ ] Split them in `packages` somehow logically (using navigation as main sorting base in stead of which actor is looking)
- [ ] Add new version to moodle
- [ ] Make an opponent review for those "bimbos" (SivihoKlubik)
