### ISSUE TITLE
Preparations for consultation no.3

### ISSUE THREAD

**Issue by GlycerolVeinz** [GlycerolVeinz/sinSemestralWork#3]
# Consultation no.3

Consultation with the instructor on the first part of the analysis.

## Tasks (what to prepare)
- [x] **Business Goals (BG)**
@FrysarovaKaterina 

- [x] **Justification of the Economic Feasibility of the Project**
@zlochina 
*Arseniy*

    - [x] Costs (TCO, etc.)
    - [x] Benefits (financial, other)
    - [x] Unit costs (e.g., average cost per user/year, one sold ticket, one completed order, one loan provided, etc.)

- [x] **Models**
@anokhver 
@GlycerolVeinz 

  - [x] **Business Domain Model** (using UML class diagram in EA)

  - [x] **Business Process Model** (using UML activity diagram in EA)

  - [x] **Business Requirements (BRQ)** including links to business goals (using the requirements diagram in EA)

Within 3 calendar days (D+3) from the day of the exercise:

- Submit the business analysis of the team project electronically (RTF/DOCX + PDF) with the instructor's comments from the consultation incorporated.

**Comment by GlycerolVeinz** [comment]
I will create new branch just for these tasks

**Comment by GlycerolVeinz** [comment]
The consultation3/business was created.
Short .md file was added so that we have a place to put our results

But first, start working on your solo home works, then we will assign tasks for the team.

**Comment by GlycerolVeinz** [comment]
**Crucial points:**
- Make "business goals" before  Business requirements
- Think about when should the customer pay and to whom.
- Make only the most important processes, _mainly those that involve money_

**Comment by anokhver** [comment]
I would like to propose changing a few names in the model diagrams to make them more appropriate and professionally descriptive. I will be using the updated names in the models constructed in EA #

**Comment by GlycerolVeinz** [comment]
# Remarks for 
## BRQ
- remove tips from app
- add description to BRQ codes 
## Process models
- add redirection of pay for customers (they pay club in cash, club moves it to their account)

**Comment by anokhver** [comment]
**Remark on Business Process Model (Mock Example Diagram):**

I disagree with the activity just before the end. The process shouldn't end with payment for the reservation. Instead, the reservation should be paid in advance (at least partially) to prevent no-show reservations.

**Comment by panyuars** [comment]
Unit cost/cost per customer seems redundant in the context of our application as the price does not depend on the number of users unless the unexpectedly high volume requires more computation power. The only exception is the CAC (Customer Acquisition Cost), which determines how much money we spend for attracting 1 customer through marketing.
