### ISSUE TITLE
Tasks - 10.05.2024

### ISSUE THREAD

**Issue by GlycerolVeinz** [GlycerolVeinz/sinSemestralWork#4]
# Tasks
- [x] Make all of the preparations for 3rd consult
    - details can be found in #3 
- [x] Make a status presentation
    - [x] Presentation itself
    - [x] gather toggl reports from the team

**Comment by GlycerolVeinz** [comment]
Please leave a comment here if you had **ANY** problems during your tasks

**Comment by GlycerolVeinz** [comment]
My problems in no particular order:
- Understanding difference between BG and BRQ

**Comment by anokhver** [comment]
I faced difficulties understanding what should be included in the Business Domain Model. Initially, I was unsure how deeply to describe classes and their attributes, as well as which application functionality to focus on during modeling

**Comment by GlycerolVeinz** [comment]
@GlycerolVeinz create new issue (tasks)
