### ISSUE TITLE
Tasks - 15.10.2024

### ISSUE THREAD

**Issue by GlycerolVeinz** [GlycerolVeinz/sinSemestralWork#6]
# Tasks
- [x] Remake business goals @FrysarovaKaterina 
    - [x] Make them as a template
    - [x] Make them more concrete / more relatable to our project (get inspired by initial vision's presentation)
- [x] Specify business requirements @GlycerolVeinz 
    - [x] add notes or explanation to each one
- [x] Redraw models @anokhver 
    - [x] Domain model should have non-oriented arrows and no methods
    - [x] Business processes should have constraints written in different style
- [x] Create new wiki pages @GlycerolVeinz 
    - [x] Initial business part that we presented with remarks of Ing.Komarek
    - [x] New reworked business part

**Comment by GlycerolVeinz** [comment]
Task complete, all the work can be seen at v0.0.3 wiki page
